import { MigrationInterface, QueryRunner } from "typeorm";

export class TableRevamp1777121018424 implements MigrationInterface {
    name = 'TableRevamp1777121018424'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_1167f1ebc206b27f4e992aa66d0"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_dd2364265f3bd8906f93d8675a8"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "dateTime"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "transaction_category_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "transaction_category_name"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "transaction_name"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "transaction_note"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "transaction_type_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "transaction_type_name"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "account_to_deduct_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "account_to_deduct_name"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "budget_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "budget_name"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "account_to_add_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "account_to_add_name"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "number_of_installment"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "total_installment_amount"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "interest_rate"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "account_class_id"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "account_class_name"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "account_type_id"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "account_type_name"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "goal_amount"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "network_id"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "network_name"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "credit_limit"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "cash_advance_limit"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "billing_date"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "due_date"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "start_date"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "end_date"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "randId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "datetime" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "transaction_category" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "note" character varying`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "transaction_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "transaction_account" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "receiving_account" character varying`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "receiving_category" character varying`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "saving_name" character varying`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "account_type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "provider" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "initial_balance" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "amount" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "current_balance"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "current_balance" numeric(15,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "user_id" character varying NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "user_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "current_balance"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "current_balance" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "user_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "amount" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "initial_balance"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "provider"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP COLUMN "account_type"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "saving_name"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "receiving_category"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "receiving_account"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "transaction_account"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "transaction_type"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "note"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "transaction_category"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP COLUMN "datetime"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "randId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "end_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "start_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "due_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "billing_date" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "cash_advance_limit" integer`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "credit_limit" integer`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "network_name" character varying`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "network_id" integer`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "goal_amount" integer`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "account_type_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "account_type_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "account_class_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "account_class_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD "interest_rate" integer`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "total_installment_amount" integer`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "number_of_installment" integer`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "account_to_add_name" character varying`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "account_to_add_id" integer`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "budget_name" character varying`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "budget_id" integer`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "account_to_deduct_name" character varying`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "account_to_deduct_id" integer`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "transaction_type_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "transaction_type_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "transaction_note" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "transaction_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "transaction_category_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "transaction_category_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD "dateTime" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isActive" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "users" ADD "lastName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "firstName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_dd2364265f3bd8906f93d8675a8" FOREIGN KEY ("account_to_add_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_1167f1ebc206b27f4e992aa66d0" FOREIGN KEY ("account_to_deduct_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
